### YamlMime:YamlDocument
documentType: LandingData
title: Ansible on Azure Documentation
metadata:
  title: Ansible on Azure Documentation - Tutorials and reference
  meta.description: Learn how to use Ansible to automates cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 12/18/2017
  ms.author: tarcher
abstract:
  description: Use Ansible to automates cloud provisioning, configuration management and application deployments.
sections:
sections:
- title: Quickstarts
  items: 
  - type: paragraph
    text: Configure Ansible and use it to create a Linux VM in Azure.
  - type: list
    style: icon48
    items: 
    - image: 
        src: https://docs.microsoft.com/en-us/azure/media/index/azure_dev-9.svg
      text: Install Ansible
      href: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ansible-install-configure
    - image: 
        src: https://docs.microsoft.com/en-us/azure/media/index/VirtualMachine.svg
      text: Create a Linux VM
      href: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ansible-create-vm
- title: Step-by-Step Tutorials
- title: Samples
- title: Reference
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Ansible modules for Azure
      html: <p><a href="http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html">Manage Azure Container Service Instances</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html">Manage Azure Function Apps</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html">Manage Azure load balancers</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_storageaccount_module.html"></a></p><p><a href="Manage Azure storage accounts"></a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html">Manage Azure virtual machines</a></p><p><a href="http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure"></a>See all Ansible modules for Azure</p>