### YamlMime:Landing

title: Ansible on Azure documentation
summary: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.

metadata:
  title: Ansible on Azure documentation
  description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: azure
  ms.service: ansible
  ms.topic: landing-page
  author: TomArcherMsft
  ms.author: tarcher
  ms.date: 09/11/2019

landingContent:
  # Card
  - title: About Ansible on Azure
    linkLists:
      - linkListType: overview
        links:
          - text: About Ansible on Azure
            url: ansible-overview.md

  # Card
  - title: Install and Configure Ansible
    linkLists:
      - linkListType: quickstart
        links:
          - text: Deploy Ansible solution template to CentOS
            url: ansible-deploy-solution-template.md
          - text: Install Ansible on Linux virtual machines
            url: /azure/virtual-machines/linux/ansible-install-configure
      - linkListType: tutorial
        links:
          - text: Run playbooks in Cloud Shell
            url: ansible-run-playbook-in-cloudshell.md
          -text: Configure a dynamic inventory
            url:  ansible-manage-azure-dynamic-inventories.md

  # Card
  - title: Manage Virtual Machines
    linkLists:
      - linkListType: quickstart
        links:
          - text: Configure Linux virtual machines
            url: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
          - text: Manage Linux virtual machines
            url: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
      - linkListType: tutorial
        links:
          - text: Create and configure Linux virtual machine
            url: /azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json

  # Card
  - title: Manage Virtual Machine Scale Sets
    linkLists:
      - linkListType: tutorial
        links:
          - text: Configure virtual machine scale sets
            url: ansible-create-configure-vmss.md
          - text: Deploy applications to virtual machine scale sets
            url: ansible-deploy-app-vmss.md
          - text: Automatically scale virtual machine scale sets
            url: ansible-auto-scale-vmss.md
          - text: Update custom image
            url: ansible-vmss-update-image.md

  # Card
  - title: Manage Virtual Networks
    linkLists:
      - linkListType: tutorial
        links:
          - text: Configure peering
            url: ansible-vnet-peering-configure.md
          - text: Configure route tables
            url: ansible-create-configure-route-table.md

  # Card
  - title: Manage AKS
    linkLists:
      - linkListType: tutorial
        links:
          - text: Create and manage Azure Kubernetes Service clusters
            url: ansible-create-configure-aks.md