- name: Ansible on Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ./ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install and configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutorials 
  items:
  - name: Create complete Linux VM
    href: /azure/virtual-machines/linux/ansible-create-complete-vm
    maintainContext: true
  - name: Run a playbook in Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Manage your Azure dynamic inventories
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
- name: Samples
  items:
    items:
    - html: <a href="https://github.com/Azure-Samples/ansible-playbooks">Ansible Playbook on Azure</a>.
    - html: <a href="https://galaxy.ansible.com">Ansible Galaxy</a>.
- name: Reference 
  items:
  - name: Ansible modules for Azure
    href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
  - name: Ansible reference
    href: http://docs.ansible.com/ansible/latest/dev_guide/index.html
- name: Resources
  items:
  - name: Tools for using Ansible
    href: ./ansible-tools.md
- name: Tools
  items:
    - html: <a href="./ansible-tools.md">Tools for using Ansible with Azure</a>.
    - html: <a href="./ansible-matrix.md">Ansible modules and features matrix</a>.
- title: Releases
  items:
    - html: <a href="https://github.com/ansible/ansible/releases">Official release</a>
    - html: <a href="https://galaxy.ansible.com/Azure/azure_modules/">Playbook Role azure_module</a>
    - html: <a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">Playbook Role azure_preview_module</a>
    - html: <a href="./ansible-matrix.md">Feature matrix</a>