- name: Ansible on Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install and configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutorials 
- name: Concepts
- name: Samples
- name: Reference 
- name: Resources
  items:
  - name: Tools
    href: ./ansible-tools.md
  - name: Ansible home
    href: https://ansible.com