- name: Ansible on Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ansible-overview.md
- name: Quickstarts
  expanded: true
- name: Tutorials 
- name: Concepts
- name: Samples
- name: Reference 