- name: Ansible on Azure documentation
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ./ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Deploy Ansible solution template to CentOS
      href: ./ansible-deploy-solution-template.md
    - name: Install Ansible on Linux virtual machines
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Configure Linux virtual machines
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
    - name: Manage Linux virtual machines
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm
      maintainContext: true
    - name: Run playbooks in Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
- name: Tutorials 
  items:
  - name: Azure Kubernetes Service (AKS)
    items:
    - name: Configure AKS clusters
      href: ./ansible-create-configure-aks.md
    - name: Configure Azure CNI networking
      href: ./ansible-aks-configure-cni-networking.md
    - name: Configure kubenet networking
      href: ./ansible-aks-configure-kubenet-networking.md
    - name: Configure RBAC role in AKS cluster
      href: ./ansible-aks-configure-rbac.md
  - name: App Service
    items:
    - name: Configure an app in Azure Web Apps
      href: ./ansible-create-configure-azure-web-apps.md
    - name: Scale Azure Web Apps
      href: ./ansible-scale-azure-web-apps.md
  - name: Application Gateway
    items:
    - name: Configure Azure Application Gateway
      href: ./ansible-create-configure-application-gateway.md
  - name: Azure Cache for Redis
    items:
    - name: Configure a cache
      href: ./ansible-azure-cache-for-redis-create-configure.md
  - name: Azure HDInsight
    items:
    - name: Configure a cluster in Azure HDInsight using Ansible
      href: ./ansible-azure-hdinsight-configure.md
  - name: Azure Service Bus
    items:
    - name: Configure a queue
      href: ./ansible-azure-service-bus-configure-queues.md
    - name: Configure a topic
      href: ./ansible-azure-service-bus-configure-topics.md
  - name: Databases
    items:
    - name: Configure Azure DB for MySQL
      href: ./ansible-create-configure-mysql.md
    - name: Configure Azure Cosmos DB
      href: ./ansible-cosmos-db-configure.md
  - name: DevTest Labs
    items:
    - name: Configure a lab in Azure DevTest Labs
      href: ./ansible-devtest-labs-create-configure.md
  - name: Dynamic inventory
    items:
    - name: Manage dynamic inventories
      href: ./ansible-manage-azure-dynamic-inventories.md
  - name: Virtual network
    items:
    - name: Configure route tables
      href: ./ansible-create-configure-route-table.md
    - name: Configure Azure VNet peering
      href: ./ansible-vnet-peering-create-configure.md
  - name: Virtual Machines Scale Sets
    items:
    - name: Configure virtual machine scale sets
      href: ./ansible-create-configure-vmss.md
    - name: Deploy to virtual machine scale sets
      href: ./ansible-deploy-app-vmss.md
    - name: Autoscale virtual machine scale sets
      href: ./ansible-auto-scale-vmss.md
- name: Reference
  items:
  - name: Playbook roles
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Releases and features
    href: ./ansible-matrix.md  
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Load balancers
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtual machines
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: All modules for Azure
    href: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure
- name: Tools
  items:
  - name: Visual Studio Code extension for Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
